# Generated by Django 2.2.1 on 2019-05-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('school', models.CharField(max_length=124)),
                ('department', models.CharField(max_length=124)),
                ('score', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
