# Generated by Django 2.2.1 on 2019-05-20 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='communication',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='marking',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='objectivity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='quality',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete='deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='professor',
            field=models.ForeignKey(on_delete='deleted', to='professors.Professor'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='score',
            field=models.FloatField(),
        ),
    ]
