# Generated by Django 2.2.1 on 2019-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_professor_comments_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='communication',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='marking',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='objectivity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='quality',
            field=models.FloatField(default=0),
        ),
    ]
