# Generated by Django 2.2.1 on 2019-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_auto_20190523_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anonymity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='communication',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='marking',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='objectivity',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='quality',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], decimal_places=0, default=0, max_digits=1),
        ),
    ]
