# Generated by Django 2.2.1 on 2019-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0012_auto_20190528_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
