# Generated by Django 2.2.1 on 2019-05-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0013_comment_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
