# Generated by Django 2.2.1 on 2019-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0015_auto_20190529_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
